### ISSUE TITLE
Errors/recovery in Ingest

### ISSUE THREAD

**Issue by kdid** [nulib/meadow#1035]
### Description

When ingesting large batches sometimes the batch gets stuck or hangs and there is no error information anywhere, nor is it clear how to troubleshoot the ingest.

We need to make sure it is possible to identify and debug errors in the ingest and also document how/where to do that as well as to report to the user error information where appropriate. Also we need to ensure the app recovers in a reasonable way after this situation occurs.

Also, we should make sure our docs include troubleshooting steps. (And that there are troubleshooting steps)

related to: https://github.com/nulib/repodev_planning_and_docs/issues/352

### Done Looks Like
- [x] Make sure ingest can respond appropriately and recover or give info about error situations
      - If it does not, try to identify error situation and write issues with specific direction
        - opened issue: https://github.com/nulib/repodev_planning_and_docs/issues/1106
        - opened issue: https://github.com/nulib/repodev_planning_and_docs/issues/1107
- [x] Try to cause an error situation and see if it's reported/handled.
  - Recovery strategy to be addressed in: https://github.com/nulib/repodev_planning_and_docs/issues/1106
- [x] Verify batch update can scale to 25,000+ records
  - Encountered issues so opened: https://github.com/nulib/repodev_planning_and_docs/issues/1111
https://github.com/nulib/repodev_planning_and_docs/issues/1113
- [ ] Document troubleshooting steps
    - Including: 
        - commands that can be run to identify problems (ex: queue status...)
        - database queries that can be run
        - location and names of log files and example filters.

**Comment by kdid** [comment]
Reopening. This got closed somehow. We still need to deal with not ending up with spinning blank screen if an error occurs.

**Comment by kdid** [comment]
Example: Database error at record 5000+ stops and hangs the whole batch....

```
[error] Postgrex.Protocol (#PID<0.578.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.103.0> timed out because it queued and checked out the connection for longer than 15000ms

#PID<0.103.0> was at location:

    :prim_inet.recv0/3
    (postgrex 0.15.5) lib/postgrex/protocol.ex:2838: Postgrex.Protocol.msg_recv/4
    (postgrex 0.15.5) lib/postgrex/protocol.ex:1880: Postgrex.Protocol.recv_bind/3
    (postgrex 0.15.5) lib/postgrex/protocol.ex:1772: Postgrex.Protocol.bind_execute/4
    (db_connection 2.2.2) lib/db_connection/holder.ex:316: DBConnection.Holder.holder_apply/4
    (db_connection 2.2.2) lib/db_connection.ex:1255: DBConnection.run_execute/5
    (db_connection 2.2.2) lib/db_connection.ex:595: DBConnection.execute/4
    (ecto_sql 3.4.5) lib/ecto/adapters/postgres/connection.ex:80: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:544: Ecto.Adapters.SQL.execute!/4
    (ecto_sql 3.4.5) lib/ecto/adapters/sql.ex:526: Ecto.Adapters.SQL.execute/5
    (ecto 3.4.5) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
    (ecto 3.4.5) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (ecto 3.4.5) lib/ecto/repo/queryable.ex:112: Ecto.Repo.Queryable.one/3
    (meadow 0.1.0) lib/meadow/data/schemas/types/coded_term.ex:33: Meadow.Data.Types.CodedTerm.retrieve_term/1
    (ecto 3.4.5) lib/ecto/type.ex:923: Ecto.Type.process_loaders/3
    (ecto 3.4.5) lib/ecto/repo/queryable.ex:378: Ecto.Repo.Queryable.struct_load!/6
    (ecto 3.4.5) lib/ecto/repo/queryable.ex:210: anonymous fn/5 in Ecto.Repo.Queryable.preprocessor/3
    (elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ecto 3.4.5) lib/ecto/repo/queryable.ex:197: Ecto.Repo.Queryable.execute/4
    (ecto 3.4.5) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
```
